### PR TITLE
Added autoScroll option to Carousel component

### PR DESCRIPTION
**Pull request by mmarfat**
### Description
This pull request introduces the `autoScroll` feature to the Carousel component, similar to the previously implemented `autoplay` feature [#316].

For more details on different options you can refer to [Embla Carousel documentation](https://www.embla-carousel.com/plugins/auto-scroll/).

### Example Usage
An example has been provided in the [docs](https://github.com/snehilvj/dmc-docs/pull/95).

If you encounter any issues or have any suggestions please let me know.

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @mmarfat 

This is fantastic!  Nice new feature, complete with tests and docs :trophy:

I just need to look into one thing before we proceed: the upstream [Mantine library](https://mantine.dev/x/carousel/) currently locks the Embla Carousel dependency to V7, while the autoScroll feature you've implemented is part of V8. We'll need to check for any issues with the different versions.

If we find there are compatibility concerns, no worries—we can keep this as a draft PR and revisit it as soon as Mantine catches up to you!

**Comment by mmarfat** [comment]
Thanks @AnnMarieW.

No worries. If I can help with anything please let me know.

**Comment by AnnMarieW** [comment]
@alexcjohnson 
What are your thoughts on this PR -- about using a version of a dependency that has not been tested in Mantine yet?

**Comment by AnnMarieW** [comment]
> here is the lock you're referring to? I just see [>=7.0.0](https://github.com/mantinedev/mantine/blob/fbcee929e0b11782092f48c1e7af2a1d1c878823/packages/%40mantine/carousel/package.json#L49) which allows v8.

Oh, that's interesting... It shows a lock in their docs:   https://mantine.dev/x/carousel/
image

**Comment by alexcjohnson** [comment]
I don't see anything listed as a breaking change in https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0 so this feels fairly low-risk to me. If you've tried it and don't see any issues I'd say we should accept this change.

**Comment by AnnMarieW** [comment]
Thanks for the PR @mmarfat 
## :woman_dancing:

**Pull request merged**
