### PR TITLE
Add prop setter for stepper active state

### PR DESCRIPTION
**Pull request by ondave**
Any reason not to add a prop setter for the active state?. Then you can do something like this in response to interacting with the stepper directly:
```

@callback(
    Output("my-text-element", "value"),
    Input("stepper", "active"),
    prevent_initial_call=True,
)
def update_stepper(current_step):
    return f"I am on step {current_step}"
```

### CODE REVIEW

**Comment by ondave** [comment]
BTW - thanks for this library - I am a big fan of mantine, great to have for Dash as well and up to date with v7.

**Comment by snehilvj** [comment]
Thanks @ondave for your feedback and this PR. I'm happy to merge this PR if you can update it to only include the .tsx file.

**Comment by AnnMarieW** [comment]
@ondave 

Thanks for this PR! I was reviewing it to assist  getting it across the finish line.   However, it looks like you can trigger a callback using the `active` prop with the current version of  dmc (.14.4.0)

You can see a live minimal example here:  https://py.cafe/amward/dash-mantine-stepper-guide

If you meant a different use case, can you let us know?

**Comment by AnnMarieW** [comment]
Looks like this is stale - closing for now.

**Pull request closed without merging**
