### PR TITLE
Add MonthPickerInput & YearPickerInput #255

### PR DESCRIPTION
**Pull request by stpnvkirill**
2 components have been added:

https://mantine.dev/dates/month-picker-input/
https://mantine.dev/dates/year-picker-input/

### CODE REVIEW

**Comment by Ferreira-B** [comment]
Any news on this? It would be a very nice feature to have in DMC.

**Comment by michaelrussell4** [comment]
Yes, just what I was looking for. Glad someone added it. Please merge.

**Comment by hdowens** [comment]
Any update on this? Would be super useful

**Comment by AnnMarieW** [comment]
Hi @stpnvkirill 

Sorry for the delay - this has been a popular request!  

This PR looks really good - just needs a few minor updates, then it's good to go.

- The component names  need to be changed to `MonthPickerInput` and `YearPickerInput` since the upstream Mantine library has both `MonthPicker` and `MonthPickerInput` components and we may want to include both versions at some point in the future.
- Remove the `console.log`
- update with the latest changes from the dmc master branch
- add a Changelog enttry. 


Let me know if you would like to make the updates.  I could also make the changes if you prefer since you have enabled maintainers to edit. 

@snehilvj - This would be a nice addition - I verified that all the examples in the upstream Mantine docs work so adding this the dmc-docs will be easy.

**Comment by stpnvkirill** [comment]
@AnnMarieW Hello! 

I have corrected the code

**Comment by AnnMarieW** [comment]
@stpnvkirill 

Thank for the updates!  Could you please exclude the package-lock.json file?  
Next, I'll run this updated version with the docs app to make sure everything works over there - then it will be ready for @snehilvj's final review .

I'm looking forward to getting this into the next release!

**Comment by AnnMarieW** [comment]
closes #255

**Comment by stpnvkirill** [comment]
@AnnMarieW Please tell me what it means to exclude the package-lock file.json?

Do you want me to delete this file? `git rm --cached package-lock.json`

**Comment by AnnMarieW** [comment]
@stpnvkirill Unless you changed the dependencies, the package-lock.json file  should not be committed and pushed in the PR.  I’m not sure how to undo that, but the file can’t be deleted - it needs to remain unchanged from the current version on the main branch.

**Comment by snehilvj** [comment]
I tried to handle the package-lock.json file from the Github UI but got that wrong. Will merge this PR for now and will handle it in a commit on top of this merge.

**Comment by snehilvj** [comment]
Thanks @stpnvkirill  and Ann for this PR and review respectively.

**Pull request merged**
