### PR TITLE
add disabled to Fieldset

### PR DESCRIPTION
**Pull request by AnnMarieW**
Hi @snehilvj 
Can we include this small update in the next release?
@MichaelODeli has the [docs PR](https://github.com/snehilvj/dmc-docs/pull/64) ready to merge after this is released as well :tada:

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Here is a sample app to give it a try
image

```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)


component = dmc.Fieldset(
    children=[
        dmc.TextInput(label="Your name", placeholder="Your name"),
        dmc.TextInput(label="Email", placeholder="Email"),
        dmc.Group(
            [
                dmc.Button('Send')
            ],
            justify='flex-end'
        )
    ],
    legend="Personal information",
    disabled = True,
    m=20
)


app.layout = dmc.MantineProvider([
    component
])

if __name__ == "__main__":
    app.run(debug=True)

```

**Review by alexcjohnson — APPROVED** [review]
💃

**Comment by sssaha** [comment]
image
Whenever I try the fieldset - as part of a drawer element - the heading does now show up like shown in the documentation

**Comment by sssaha** [comment]
@AnnMarieW @snehilvj  - just tagging as the issue is closed 
Am I doing something stupid?

**Comment by AnnMarieW** [comment]
@sssaha What version are you using?  Can you please provide a complete minimal example that reproduces the issue?   Hard to tell what the problem is just from an image.

**Pull request merged**
